baseurl = "https://dwmkerr.com/"
languageCode = "en-uk"
Title = "dwmkerr.com"
# Copyright notice. This is displayer in the footer.
copyright = "Copright &copy; Dave Kerr"
theme = "hugo_theme_pickles"

# Use our Google Analytics G4A tag. The 'G-' at the beginning lets Hugo know
# that this is G4A, rather than 'UA-'.
googleAnalytics = "G-XNRSGLYJRM"

# Allow Markdown to contain HTML (this is used for tables, some URLs etc.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "dwmkerr"
  linkedin = "dwmkerr"
  bookurl = "https://amzn.to/4ho0F91"
  # Disqus shortname
  disqus = "dwmkerr"
  author = "Dave Kerr"
  authorwebsite = "dwmkerr.com"
  avatar = "/images/avatar.jpeg"
  # contact = "mailto:dwmkerr@gmail.com"
  bio = "Climber, Coder, Technology Consultant. Views expressed are my own."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Articles on the craft of software development."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/images/favicon.ico"
  custom_css = ["/css/custom.css"]

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Speaking"
    url = "/page/speaking/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[Permalinks]
    post = "/:slug"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
